  microservice:
  library-payment-service:
    endpoints:
      endpoint:
        uri: http://LIBRARY-PAYMENT-SERVICE/payment/doPayment
  library-order-service:
    endpoints:
      endpoint:
        uri: http://LIBRARY-ORDER-SERVICE/order/bookOrder
