eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost    
    
microservice:
  library-payment-service:
    endpoints:
      endpoint:
        uri: http://LIBRARY-PAYMENT-SERVICE/payment/doPayment
  library-order-service:
    endpoints:
      endpoint:
        uri: http://LIBRARY-ORDER-SERVICE/order/bookOrder